In [125]:
import math

In [3]:
math.sin(10)

-0.5440211108893698

In [4]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
a = [1,2,3,4,5]

In [7]:
a*2 # will duplicate the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [11]:
%time [a*2 for a in a]

CPU times: total: 0 ns
Wall time: 0 ns


[2, 4, 6, 8, 10]

In [12]:
arr = np.array(range(10))

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
%time arr**2

CPU times: total: 0 ns
Wall time: 0 ns


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
# Time to process

In [22]:
%timeit arr = [a for a in range(100000)]

10.1 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%timeit [a**2 for a in arr]

19.2 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%timeit arr = np.array(range(100000))

23.6 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%timeit arr**2

231 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
# Above is the time comparision for list and numpy array

### Dimension and  Shape

- Dimension means how many index you require to get an element
  - 1 D Array
  - 2 D Array

`array.ndim`

### Dimension 1 
[1,2,3,4,5,6]
### Dimension 2
[[1,2],[3,4],[5,6]]
### Dimension 3
[[[1,2],[3,4]],[[5,6],[7,8]]]



matrix provided in numpy should be in proper shape


In [46]:
a1 = [1,2,3,4,5,6]

In [30]:
arr = np.array(a1)

In [31]:
arr

array([1, 2, 3, 4, 5, 6])

In [32]:
arr.ndim

1

In [42]:
a2 = [[1,2],[3,4],[5,6]]

In [43]:
arr = np.array(a2)

In [44]:
arr.ndim

2

In [45]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
a3 = [[[1,2],[3,4]],[[5,6],[7,8]]]

In [37]:
arr = np.array(a3)

In [38]:
arr.ndim

3

In [39]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Shape

Shape is the size of an array

`array.shape`

Return RxC



In [48]:
arr.shape

(3, 2)

In [50]:
arr[0].shape

()

In [51]:
range(1000000).shape

AttributeError: 'range' object has no attribute 'shape'

In [52]:
np.array(range(1000000)).shape

(1000000,)

# Quize

In [53]:
arr = np.array(range(10))

In [54]:
arr.ndim

1

In [55]:
arr.shape

(10,)

# Task

- Create a list with 10 Elements
- Convert it into numpy array
- add the complete list by 10
- create a 2D numpy array
- check the shape and dimension of the array

In [66]:
arr = [i for i in range(10)] # Creating the list of 10 elements

In [58]:
narr = np.array(arr) # converting the list to numpy array

In [59]:
narr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
narr+10 # Adding the complete liist by 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
arr2d = np.array([[1,2,3],[4,5,6]]) #2D numpy array

In [64]:
arr2d.ndim # detecting the dimension

2

In [65]:
arr2d.shape #detecting the shape of an array

(2, 3)

### Arange
Directly create the numpy array

`np.arange(start,end,step_size)`


end is non inclusive

range dosen't support floating step size but arange does

In [67]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [69]:
range(1,2,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [70]:
np.arange(1,2,0.5)

array([1. , 1.5])

# Quize

In [71]:
arr = np.arange(5)

In [72]:
arr[2:4] = 0

In [73]:
print(arr)

[0 1 0 0 4]


# Data Type in Numpy

In [75]:
arr = np.array([1,2,3,4,5,6])

In [76]:
arr.dtype

dtype('int32')

In [77]:
arr = np.array([1,2,3,4,5,6.0])

In [78]:
arr.dtype

dtype('float64')

In [79]:
arr = np.array([1,2,3,4,5,"6.0"])

In [80]:
arr.dtype

dtype('<U11')

In [81]:
arr = np.array([1,2,3,4,5,6],dtype=float) # forcefully converting all the data type of your choice

In [82]:
arr.dtype

dtype('float64')

In [83]:
arr = np.array([1,2,3,4,5,"6.0"],dtype=str)

In [84]:
arr.dtype

dtype('<U3')

In [85]:
arr = np.array([1,2,3,4,5,6],dtype=float)

In [86]:
arr.dtype

dtype('float64')

In [87]:
arr.astype("str")

array(['1.0', '2.0', '3.0', '4.0', '5.0', '6.0'], dtype='<U32')

In [88]:
arr.astype("int")

array([1, 2, 3, 4, 5, 6])

In [89]:
arr.astype("int64")

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [91]:
arr.astype("float")

array([1., 2., 3., 4., 5., 6.])

### Task 
Create an array of float values and convert it into str

In [92]:
arr = np.array([1.4,6.12345,12345.123])

In [93]:
arr.astype("float")

array([1.4000000e+00, 6.1234500e+00, 1.2345123e+04])

In [94]:
arr.astype("str")

array(['1.4', '6.12345', '12345.123'], dtype='<U32')

In [95]:
np.array([1.4,6.12345,12345.123],dtype=float)

array([1.4000000e+00, 6.1234500e+00, 1.2345123e+04])

# Indexing and Slicing - It is exactly same as list

In [96]:
arr = [1,2,3,4,5,6,7,8,10]

In [97]:
arr[2]

3

In [101]:
arr[-7]

3

In [102]:
np.array(arr)[3]

4

In [103]:
np.array(arr)[-7]

3

In [105]:
np.array(arr)[[2,5,7]] # List of index will take only selective set of index

array([3, 6, 8])

In [107]:
np.arange(1,100)[1:6] #last element is not included 

array([2, 3, 4, 5, 6])

### Quize

In [110]:
a = np.arange(0,6)

In [111]:
a

array([0, 1, 2, 3, 4, 5])

In [112]:
a[4:] = 10

In [113]:
a

array([ 0,  1,  2,  3, 10, 10])

# NPS Case Study
- Query1 : All values that are less than 6 in below array

In [114]:
#all values that are less than 6 in below array
m1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [119]:
query = m1<6 # Create a query for the question

In [121]:
m1[query] # pass the query to the array index

array([1, 2, 3, 4, 5])

## Quize

In [122]:
a = [1,2,3,4,5,6,7,8]
b = [100,200,300]


In [123]:
a[2:] = b[::-1]

In [124]:
a

[1, 2, 300, 200, 100]